# -*- coding: utf-8 -*-
"""IndInflationPrediction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bZTVqV3ebCa5QS5uneOaXOhShDr7MTh6
"""

import numpy as np
import pandas as pd
from sklearn import metrics
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
regression_data = pd.read_csv(r'/content/drive/MyDrive/Inflation/inflation_data_ind.csv')
X = regression_data['Year']
y = regression_data['Rate']
rng = np.random.RandomState(1)
regr = DecisionTreeRegressor(max_depth=2)
X= np.float32(X)
y = np.float32(y)
X = np.array(X)
X = X.reshape(-1, 1)
regr.fit(X, y)
new_X = [[2023]]
result = regr.predict(new_X)
print("Prediction : " + str(result))